# Generated by Django 2.2.4 on 2019-08-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='category',
            new_name='category_id',
        ),
    ]
